apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keysboard
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
  - ./images.yml
patches:
  - patch: |
      apiVersion: argocd-image-updater.argoproj.io/v1alpha1
      kind: ImageUpdater
      metadata:
        name: keysboard
        namespace: argocd
    target:
      kind: ImageUpdater
