apiVersion: apps/v1
kind: Deployment
metadata:
  name: codexlb
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: codexlb
  template:
    metadata:
      labels:
        app: codexlb
    spec:
      containers:
        - name: codexlb
          image: ghcr.io/soju06/codex-lb:beta
          ports:
            - containerPort: 2455
          env:
            - name: CODEX_LB_DATA_DIR
              value: /var/lib/codex-lb
          volumeMounts:
            - mountPath: /var/lib/codex-lb
              name: codexlb-pvc
      volumes:
        - name: codexlb-pvc
          persistentVolumeClaim:
            claimName: codexlb-pvc
