apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codexlb
resources:
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
images:
  - name: ghcr.io/aafqaq/codex-lb-enhanced
    newTag: latest
    digest: sha256:e495395eca492d6db32f25c351685516abd426d40c020769ab5e21fb6dbba7a8
