apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codexlb
resources:
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
images:
  - name: ghcr.io/aafqaq/codex-lb-enhanced
    newTag: latest
    digest: sha256:ea17ab29d39fb11bf0f9a4cd05c3e6ed8bb6c4c197192e57b50befd5e4344bd0
