apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codexlb
resources:
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
images:
  - name: ghcr.io/aafqaq/codex-lb-enhanced
    newTag: latest
    digest: sha256:a52db96eb696539c32dc86200e77716db8869d65e22d3a93007a0c34e6d3cd21
