apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: pdf
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: pdf
      images:
        - alias: stirling
          imageName: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest-fat
          commonUpdateSettings:
            updateStrategy: digest
          manifestTargets:
            helm:
              name: image.name
              tag: image.tag
