apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bro
resources:
  - ./secret.yml
  - ./rbac.yml
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
  - ./secret-auth-codeserver.yml
  - ./secret-auth-opencode.yml
images:
  - name: ghcr.io/pmh-only/bro
    newTag: latest
    digest: sha256:31fe5d6957505fecd437b733fb03736214e386b4a34f28b0e2604fe065d133a3
