apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bro
resources:
  - ./secret.yml
  - ./rbac.yml
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
  - ./secret-auth-codeserver.yml
  - ./secret-auth-opencode.yml
images:
  - name: ghcr.io/pmh-only/bro
    newTag: latest
    digest: sha256:734eadf614865e87c44f8ceb8223da280f7085786989aa90dbf6e9973e884b3a
