apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bro
resources:
  - ./secret.yml
  - ./rbac.yml
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
  - ./secret-auth-codeserver.yml
  - ./secret-auth-opencode.yml
images:
  - name: ghcr.io/pmh-only/bro
    newTag: latest
    digest: sha256:fb15915ec5ee96b9e96b0dcf0c1e79ce0cd185ab7a78c9645e97e360b6cc7c8d
