---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bro-opencode-auth-secret
  namespace: bro
spec:
  encryptedData:
    client-secret: AgCSKH9SlcuPVZd5IeykteZk425nv4gwQFMbuUtLzaMVwVi8Juz2E37ip/tsXoZGySJD1os/Uw26mzjp0tHrxUxKmJ64hyfMpMkjGh/3thUSTVFwo5tKHZxLLdHfcplaoV0iX9ZMe1Oehjfdk9fpHJPV8rWZClG0jQtGZtjq+IReNIbBopsgP7HWJVyEmXc2tJ5AXCntd3zTX2NtkynODVQALb7MjSOZ/17ZnANCHc6CpWL/qwC74L61HmPSWs1vQcVuT6xJ8MDMbAS6f/7+poM0Et+GCbOpGwt0EpwbN7tIX0krq7jB1dsbBmUznk+5W48LUOUF3s9mk8ske7L/oMI/sweeEjDypilgX0VRpl9xQPLne9q+l4TdWyhg3IOO9M0KwpwiithXkibxOtjCjezeH+Tf6NtjrOeeLTOF5Wd4TJ0+sDCwS71K6s52b8wf7PaKGPUWbCdwlAZi3Z8nebU7d7qXy6U0TUceoNZpHo2hZ00ht+aFf2Wy0wwJwUFnRTPkb4FtPOfh+BI32H+Mk2+AHkEWDl6QKWGJ0pl1CIZ3WBvVuXB2+DfnYd+Nj2EXKkdb2+gsns9/nuMATmfLG5ZdrLwVLXGAd0OXlGjFm84IwwVHva6PPrXdeRbnR1MMb+DsIFWsdSFfpzmecX21ptJuxh7i6gCG/f7dY4BptEIwyxz/jqvxymdN/4core0dX0ang0AuplXT2oFmep6vYWKy2/fxCWVmiaw+qLsPL5y3Iqb0sF4IVgtrCb7FolLy9b3ZCIToU0rIyj+hxtGmZkT9X1Ngcf7wkftvdGTEyMRU6TFf63spWNe0Jr/IuEbobck0R08Tr8hdyfbR7rzX1ms+MPEFd3v8EPbM7zdueUdk5A==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bro
      name: bro-opencode-auth-secret
      namespace: bro
    type: Opaque
