---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bro-codeserver-auth-secret
  namespace: bro
spec:
  encryptedData:
    client-secret: AgBHGry7GJsl5qXpR50XHMzdJbXEAJdXLImyMZhcI0TL4C8EXnN4hsh3Gq2OJD150wjvI24Dohl7t3BmWKiI0TRQ8xeq8FwQjgH/IIAbnrYYBBKB/naMkneStcpcYIgxpS+qSeWELHnq2o7p1EO9aVGvPyAejwkOrlKd5ECnpj4vlixPKiMaS2iFzmpL0MA+BybgOcKe2hNTJet2+wJ3wMFH+7QBihZ+58pzuoKfOSJIEvSbIJ5xDps7bfqnSfangaWc9aeUqY8t2F/9ZJPQgj3y0pHEohp2yv3AEBZQpf0VDlURDdr5xOvRRnmYDLQVNpIYwgz6s3WiQoASwNX7s7L0C5blsywvt25xvHF+NPqt9AqOJaloNDJhvneZZg9fA9S5RsCC3fSVVP9G7MbFcyHgxSXwVbZ1ZAhBCJqfd3XcF8u+ioVj99MSC/Vw1jhLSh8UqYPl+uiny9lmIqRlIrs6VHvCzc9hwj3iNqoGRIy887cvkiltpKKGE7laUGBnw1egpl7yAwvYcV/JcZDpB+FcvsOgYp7zcoL2JFR91yxFeHhTXoFIOaxEjBP3pJZXqSpc2eNYrEEbB62ecOEsuItG8yVYlBhlemUehKRX5EAJsr0TsNQiCeUedPjxcfQdg/qKGTmuKu/xKgNSJDxq5ahHTT0MhZecRi8XXPuj5Su6JF7yU6CwSxZ4IuqygpWcj8cDheQyfb7wxpQ0Ikq4yeTLLrH2mN2YXZEYCkRCmQitEkxQJGJ1KsGrl0Nm/XigTkpom4t3houR0i618QXI5fknTQMgWgaWqgnnBdfERe/nRv66GWpafVE7XRoMzatjIBOqF30rKEwP6Y+qAVPMXDBHM1AXgVwDz0Xf2GOf3UFXMw==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bro
      name: bro-codeserver-auth-secret
      namespace: bro
    type: Opaque
