---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bro-secret
  namespace: bro
spec:
  encryptedData:
    DISCORD_TOKEN: AgC4dA5r7lQv1GPTj5StZ8LNWVXFfeyb8E8zu5l5TxuDnIUot/IoIFmZrHKq+ZEfH7wYumKuTfNoUKuw8Kdow+WBboHhITq7AgySsn6xgD1RG27IVRDZgLAscXvN2AqHhq9rmMVuUahYwFf1oH0mUGz2D2CtUsdQO0GOyW+jnQxaWLf+BVPIEk3v7a4CwrvzimzU0wf9vlHdKsDOKteO5UGfKnZ4OB1GurWBYOl7lpXQGlMXjZQfgQlQJNXPJlx53nYb437r4hsHlmKe1/3thlQIRR0qlG/J68WB2poRO3JCtchFryCqIQ50sk18o8WcmnrnTiGNeKOmk36TGxiuoPudH7l2N6s/uHEMPIE4uR7Cn5YMi3KkedqlQr/5VO1PhvlJDkgwb3dAm0BPZh/RTGDhp8VT9sYSBhxQkaU/tdm3kHQDg1E+uuYuepfuFNpJ4u5TGOfGDbH+wir0vBJKLmAo8YR7y6irxNG8g1koP+vT8Dx/l42rrC2Ysnz+wcfHpP9BP/j2H8LsW7cZRWwTCJj0qZGBH5FIOaxTOirIkvjKDL3fuOb9BXf7EAAYZG43UY3dKeS9+Pg5sL1r3+iYPsHGvMb+S9LvwDG4e8IaJgQ3BuKtXA0o5MDoPmUpeq66tjXBFai4QzYbnt9pqWjnvcGWWy8QIEWJOqlc/C1XOj70/RNIFGkVAUL0XnVe4hh9qXNhVLoDaMuzY+JaOB0COSVi0GkI+Aq0udOLt+/2Q71c9eweCIqVPijNBrphUiLD0PDiAIRW23auwMj1wqVjnbfwe4zUZHQc18g=
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bro
      name: bro-secret
      namespace: bro
    type: Opaque
