apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: books-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: main
      namespace: gateway
  hostnames:
    - books.pmh.codes
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: books-frontend
          port: 3001
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - group: ""
          kind: Service
          name: books-backend
          port: 3000
          weight: 1
