apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: books
resources:
  - ./backend.yml
  - ./frontend.yml
  - ./worker.yml
  - ./ingress.yml
  - ./secret.yml
images:
  - name: ghcr.io/documentlane/doclane-frontend
    newTag: latest
    digest: sha256:1ac80c188b56ef7dfc76562b58af264de7a8972c9b1f3110159e0cc4b1f9d365
  - name: ghcr.io/documentlane/doclane-backend
    newTag: latest
    digest: sha256:9d1acf1d73c834014d68fdaa3b816d01969285faad80123c6443f3b450ff5e6f
  - name: ghcr.io/documentlane/doclane-worker
    newTag: latest
    digest: sha256:a795950f8f7d3de1284b87135a567563c66ced7deedceb2a285b9e6f0827092b
