apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway
resources:
  - ./certificate.yml
  - ./clusterissuer.yml
  - ./nginx.yml
  - ./envoy.yml
  - ./backend-policy.yml
images:
  - name: ghcr.io/pmh-only/nginx
    newTag: latest
    digest: sha256:8807f1d55ed56587d9f218792cac57f2807075dffee7b9bf4dd5d8b089055333
