apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway
resources:
  - ./certificate.yml
  - ./clusterissuer.yml
  - ./nginx.yml
  - ./envoy.yml
  - ./backend-policy.yml
images:
  - name: ghcr.io/pmh-only/nginx
    newTag: latest
    digest: sha256:84377a6376428a2b39d8484d8e843e38fb42eef465d71c8f94c55a96d9a51808
