apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-nginx-waf-config
  namespace: gateway
data:
  includes.conf: |
    Include /etc/modsecurity/modsecurity.conf
    Include /etc/modsecurity/crs/crs-setup.conf
    Include /etc/modsecurity/custom-rules.conf
    Include /etc/modsecurity/crs/rules/*.conf
  custom-rules.conf: |
    # Remove host header missing rule
    SecRuleRemoveById 920280

    # Remove content-type header limit rule
    SecRuleRemoveById 920420

    # Support more Body limits
    SecPcreMatchLimit 500000
    SecPcreMatchLimitRecursion 500000
    SecRequestBodyNoFilesLimit 1073741824

    # Allow REST/WebDAV methods
    SecAction \
      "id:9200200,phase:1,nolog,pass,t:none,\
      setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE PROPFIND PROPPATCH MKCOL COPY MOVE LOCK UNLOCK"

    # Exclude PostHog cookies from MongoDB SQLi rule
    SecRuleUpdateTargetById 942290 "!REQUEST_COOKIES_NAMES:/^ph_phc_/"

    # Allow n8n /types/credentials.json - skip LFI check for this exact path
    SecRule REQUEST_URI "@streq /types/credentials.json" \
      "id:9200201,phase:1,nolog,pass,t:none,\
      ctl:ruleRemoveById=930110,\
      ctl:ruleRemoveById=930120,\
      ctl:ruleRemoveById=930130"

    # Exclude Grafana Prometheus query body from SQLi detection
    SecRule REQUEST_URI "@beginsWith /api/ds/query" \
      "id:9200202,phase:1,nolog,pass,t:none,\
      ctl:ruleRemoveById=942100"

    # Exclude Technitium modify body from split attack detection
    SecRule REQUEST_URI "@beginsWith /api/zones/records/update" \
      "id:9200203,phase:1,nolog,pass,t:none,\
      ctl:ruleRemoveById=921130"

    # Bypass large argument count check for session replay endpoint
    SecRule REQUEST_URI "@beginsWith /api/session-replay/" \
      "id:200009,phase:1,ctl:ruleRemoveById=200007,nolog"

    # Seafile upload: allow Content-Range header and non-standard Accept header
    SecRule REQUEST_URI "@beginsWith /seafhttp/" \
        "id:200010,phase:1,nolog,pass,\
        ctl:ruleRemoveById=920450,\
        ctl:ruleRemoveById=920600"

    # Disable ModSecurity for gateway health check endpoint
    SecRule REQUEST_URI "@beginsWith /_gwhealthz" \
        "id:200011,phase:1,allow,nolog"

    # Authentik update application redirect's url
    SecRule REQUEST_URI "@beginsWith /api/v3/core/transactional/applications/" \
        "id:1001,phase:2,pass,nolog,\
        ctl:ruleRemoveTargetById=934110;ARGS:json.provider.redirect_uris.array_0.url"
