apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: bitwarden
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: bitwarden
      images:
        - alias: vaultwarden
          imageName: ghcr.io/dani-garcia/vaultwarden:latest
          commonUpdateSettings:
            updateStrategy: digest
