apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bitwarden
resources:
  - ./pvc.yml
  - ./deployment.yml
  - ./secret.yml
  - ./service.yml
  - ./ingress.yml
images:
  - name: ghcr.io/dani-garcia/vaultwarden
    newTag: latest
    digest: sha256:d626d04934cd1192ad8ced1adb975099fca78cec33ab467d2d3c923cde7f3b0c
  - name: ghcr.io/pmh-only/backpack-bitwarden2s3
    newTag: latest
    digest: sha256:1ec43bd11a022884222c6ca0708ef82c05186144ca211e791bf4dd1d6a7b0cc2
