apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meta
resources:
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/discord-query
    newTag: latest
    digest: sha256:4c51cce3bfe9c15a5759d9efc9a07ba5c21c6a3bea2903a89cd2829ecc94d02c
