apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meta-auth-secrets
  namespace: meta
spec:
  template:
    metadata:
      name: meta-auth-secrets
      namespace: meta
  encryptedData:
    client-secret: AgAqdgur6scUeqBAJyjdsbB4w9aGW/HlRBij8FIEIi8/Gkg3f2B0e67mqLmlhl2OHRttqKN4W4La+rIk8s0xWxkAyUnO+kAxfl7opmgY4m3PDEhOQeCelPlhoznq7TaN77z/azfLzX7LVvBr9Ozntpq92x2g8iJQfFyT95bM60+C4zpXLBrRjoE8IVoBJAtkZ2jrx+rETSSShOjeEIxkf/0CowxUQL4WGmdgMNKDM73sEf92yPhEYKDXAUe1Sy17ci1FvCjlYYNu6qUjZWyIltuL1IZvw6N6iHUW9NzIjUszTVd0FmZ7qYoJnp2IPdVpUl0KjmtrfY9PYUFGUWs0so0Eg6ByO+N4t9E2B7ThaNKeemamXj3cRHDKF9sav7/JMGx+Fwnln16QJqy1CyTDj/zfreEuhBXkJwQfPSYZcgeHp9b5H0/Q9exj8C+dJFkDiA9kn5ra7t5/LPs3TLqT0e0u1JMWCcHsJByQ9lPgxlg3ry9U78f6teK67jsfLXVRm7dB8kDBTmmjSheBW9lbFyswv287syAuoWsxAG0Iy4MzFlaugsgCQKgCCnIftSV3tBDk3tPc0GW2+BOEkBLHC/H1qRa+C/Hdl4oaVPVArWZvqg8NRppzuWl1MMmZQ3uugyDxBn8e3XtP+C8vOMGlBuLHQrV9JsoZtskDAfkWv36KY8CTmgRrX2jnsB4pd8JnAejtSAV/R7iE+2TAwsNCO94IaYxCNg/4RU+b6fFtpIg0jOpmpthC9ZTbanDMYZXqJ3ylgx1DiGvRNTwjxBlS8JJ87xkeEamlLNxryscLSLUrNvrnoSplw1IIXpF/elxT7mftDVbK2XJD3jBEwFgP7z+kq7jISidWsdWbYqJdt8NKiA==
