apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traffic
resources:
  - ./aggregator_cm.yml
  - ./aggregator_svc.yml
  - ./aggregator.yml
  - ./collector_cm.yml
  - ./collector.yml
  - ./ingress.yml
images:
  - name: ghcr.io/pmh-only/goaccess
    newTag: latest
    digest: sha256:c71aed901220a4a3b8492d7bd5452b5070f1a70d20d16d860144e03537f19b0b
  - name: cr.fluentbit.io/fluent/fluent-bit
    newTag: latest
    digest: sha256:d792375ca8e53be72fc25716c28f291f32c6fc6f4f31d12d0d14bc78cefe9226
  - name: ghcr.io/pmh-only/busybox
    newTag: latest
    digest: sha256:97434c3687effe0181b10bcfea51dec1a72c2ecec18068adf296c197787a2e81
