apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traffic
resources:
  - ./aggregator_cm.yml
  - ./aggregator_svc.yml
  - ./aggregator.yml
  - ./collector_cm.yml
  - ./collector.yml
  - ./ingress.yml
  - ./images.yml
patches:
  - patch: |
      apiVersion: argocd-image-updater.argoproj.io/v1alpha1
      kind: ImageUpdater
      metadata:
        name: traffic
        namespace: argocd
    target:
      kind: ImageUpdater
