apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trace
resources:
  - ./deployment.yml
  - ./secret.yml
  - ./service.yml
  - ./ingress.yml
images:
  - name: ghcr.io/rybbit-io/rybbit-backend
    newTag: latest
    digest: sha256:5a824932c8b7b16364c8ee132e29d1d9d9574445e0d1f091e6364695e117bd66
  - name: ghcr.io/rybbit-io/rybbit-client
    newTag: latest
    digest: sha256:2f6f7cbfd65f50129573b67082148b5bb00c20c04420d74ae133c1fd4dc8ac99
