apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onebus
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
  - ./statefulset.yml
images:
  - name: ghcr.io/pmh-only/onebus
    newTag: latest
    digest: sha256:e0ff37b605ca093a9e7350f9583bdf8d31fe041a79bbafd7326339b70cf1f34c
