---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: onebus-secret
  namespace: onebus
spec:
  encryptedData:
    ONEBUS_DATABASE_URL: AgAFm+bOtWYWyPDwjBttzVK3YRTHRaSMmPHkVjT+gUDRseku7iycs5i3hnJCEdqgPwGM7mxCbbYkjLDHAR2U536WHY+A7pFy+Brwd9Ab7XDt5YeDsyk+Y3NHpnk9mKnDEwmKyBrVe2Uhdl+rL2wdfmu7tCMfowovcT2N7dhzrxz1bOuHZRpyQkuG6j29NYzgGr8GMDseaXK1pLJz+5ss0KmegTbmiZuAiHsGe8uaLQpLZchzxu5XvUfa4jMt8RIdO12Q0cJTDboSzJZhOmnIwcH8w1f+s3O6+nTQyOCsOhtNqefcmzQSrwGi9VE5ofKO1YM4GaAHS6dv3Er/G6feAnGq5tWb4xvJjy0Jl3CXK3gfiyXICJL7cQqxwsjxOYN6WW9Y4nL3OnVAgnRgvaJyya6ctE0ABAc2NNg6mOR+KVUCwxXCJyzrJdzgZMJ4Fh4Y08w+Z9O71wnZNC/Epi/pUDlExWKd7+s1Zh3mEs+8HtmDt9cjm2or7r4+FAFoute3RrWSfpzs1Fg/pHvuQHQ2/2OALtbO2dwkeRamh2ajhjweJ4F2P1po1eerQPF7k4t/rLbLKLabHWqOeM2eTAzsAgl4dBs8WSH0fhySDyA0FG1atYS1Mmr1mD13BEyaVAmOH9vrQhwPMe8AyHqeH85T0xUvXWhzqV0L1JAqpgiVHC5s5afUyuSC5tOzh2KzW5rp2htKNiz8QolEnFah+Uirf4B76z/Pwx+9l/+OD5ldVaH4EfmXFIw1NqyWzRaL024gXZO8FxRt39FppjntkBo4mSoCukS7NdlLXvAbL2rQU0ENsIILa1nxug0=
  template:
    metadata:
      name: onebus-secret
      namespace: onebus
    type: Opaque
