apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: indexgen
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: indexgen
      images:
        - alias: indexgen
          imageName: ghcr.io/pmh-only/indexgen:latest
          commonUpdateSettings:
            updateStrategy: digest
