apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./grafana.yml
  - ./image-renderer.yml
  - ./ksm.yml
  - ./thanos-secrets.yml
  - ./thanos.yml
  - ./ne.yml
  - ./prometheus.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/grafana-image-renderer
    newTag: latest
    digest: sha256:7f776ebb20f82b9cd5940238da596da8caf26baf9025c2e0a991d23dd803a0e6
