apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./grafana.yml
  - ./image-renderer.yml
  - ./ksm.yml
  - ./thanos-secrets.yml
  - ./thanos.yml
  - ./ne.yml
  - ./prometheus.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/grafana-image-renderer
    newTag: latest
    digest: sha256:e925ba95a07372527cd79827381f83f3fe7895511ee46508e35fd9400b56a369
  - name: ghcr.io/pmh-only/grafana
    newTag: latest
    digest: sha256:98fff32d911af402c05738441c555eef9ebecd1c45f238b75f444f9a2d5e6f55
  - name: quay.io/prometheus/node-exporter
    newTag: latest
    digest: sha256:1b4e4438faca4dd7e001dd445d161a4a2091b0fededa84093b3a8dfeae1f1be0
  - name: quay.io/prometheus/prometheus
    newTag: latest
    digest: sha256:5ce7540c3c00ef4ab0c9d2c995c6a5b9c421f44b4a115d97a2c7af3b1c21cbb0
  - name: registry.k8s.io/kube-state-metrics/kube-state-metrics
    newTag: v2.13.0
    digest: sha256:639a1e2da549210adddc0391ff91e270e83f7873014aec53258462812f741e6f
  - name: quay.io/thanos/thanos
    newTag: main-2026-08-17-8908023
