---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mimir-secrets
  namespace: monitoring
spec:
  encryptedData:
    access_key: AgClNGnbIRJslHKwQarItb6cA5BenVUi6nUs0p19OpqZZAzPBGGe32oLRL9+P3oTn8feAhnvKj5LxobzPJdm+2y5BR5GnxqgYpP38E8qxmvIP1uAF56UUWBEO+cBoQTmzmV8JftUZlj+KZlzoTL6fR3Jh3a4DV1SmNyGrlXChHsLDt5a5aG+iHCBzXa5hVBiYuvQ5EZmuU08SlCns6deUCtCEdz3/U8SjojIwBIdmXW1Tl4rpAZ8aAaMEexz2QFJom2x82BRIyYj8SaMC/mslCvluyBB2QKG0N3meLzQC4itwpHiokNPYsUL8QY+A1a/x4Vh4tV9Yq5YyFptIi+ygdhEkwoDpk9rGLxL5AGkuIAYM4kBc1JMgPPBu3alrYD8RFueJJBHcr51tzyCkKXpJNwl33JmsYrh+JG2f6FEWqO9kpBf2s17ymjJRN6FPI80LfI5BLOaLXIqORxJGnqtTNj5E2DdUSFCdJ+6uq7ZWbfd35pBrD0xAmG+2Ak8vkwogoP57kWViYfyOHvvGOUOyDoVU05jYYIoKQtJ8ODO34grXCXPgAQGdtM4RoNI7p2k9rFJ+phCUKCKZFrzEa3kawk8MQT89aO+uyfvtrM8t01vGpXRenZRSR+RmcURkgnWEOVYCf+qKOJpujaxpbpdJYccz1pL5VGg+jZBDlE6xlJZKXY1R4lxcDma7Muy6yfrRPpLtN3sl6islg==
    secret_key: AgCcJSA82xEbdNEhNVk3QNrAhhzbmMbxLceEGlPYj5hpsH5Eq7UgvTEI3a2obgpAX5cOZR4QSaYY3cEp1nbhmEkCRCrkhosZ/25TolPba5+q2uu2ZoIFEslAFRRob5hVuMgCFRKe20aF2JW7xofj9fkA++sBD0QFCGIVHQbxhrlqLozzX8ItJQkvYjWOeCk0852Bo7P7RwQs4FF4MyNe7IgS5aLhAvQHIJGza2oc18R8g6/dTRmaj41zZIYuUjZyLcZ90+aDZWWSMdsQUOoK0EHyRrDlR76TtTN9LP4VLagG5TtrC5gsouNT3G3123MnpnzjTCq80eZtfBFwFkUts3onaBnlQyndKJ6wU9S8jl4kbQn2T5FVVtlFtpIH6r9SXTJo6XpL/rHTKLA0DU/w1vMlRcNA86raK0UGm6shYSH5h8H5dkX1SgXeC8Lw7ZDpUIrS4CFmnnj3UvrPj4LogJSBLFZ/ZXc4W/VmuKKWmvuDtBXm1msqDQ/gMjC0Lt4WTM27RCta39OSa5neetasqw7Rj2zoY8osMP0ujP2QqJDG4oc1BFcBoWPPf2owYWoqPF6I7NJisQkXCzM681JrsZxFqQZP0EMrnjXc1Oi9ygH6JceKEZk67c7Y7tQp8bUgdqxBJpOX/3bfmBLQ/OS8SIX7IYsERmb1akbpKKdH9QUPQTk7nbfSWA+0/8em6yQayMk4n8MUBxtIrsa8IYlKgA==
  template:
    metadata:
      name: mimir-secrets
      namespace: monitoring
