---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mimir-secrets
  namespace: monitoring
spec:
  encryptedData:
    access_key: AgBTH7eb3w4i4M69DsrJqD5HEct0/Vp1bVjCnwmfd2ve7VyiK/PebC5/7W87k4zDgKi4Pi6MFP4ZbJh8mtlfti1sG0aX8PSfQ3LPbapfWagy+NnxHK3EfGAvlmN1hvfS5HNmsv7l0T6Lq6dUgGlG9QD/OK28iTmGliwJcX6hUpb4HD68VK0iW7NtFFpN4KaaOWocNHWnBMySraeAFxRSfQGCaSMZ3TSOBq363OXZ2hoeeHJ+T4t0CdIyAtlXeJEMPEsof+bdoVEFXOI/3A7Eiw+hDh4zY5jAo9o/dNL21xt+LOgxawpANNSwElYdogQrkWwtZG2wHTB31BV1n6dKWSwioHEVQPSrNGb9a/BtjyEBzcZ9fCoXqMXEyjBNjUw/EfshDYLgTtp8ykv6+q0w76SXuokA5xTuKCFBi+/c6DwPknXL8pGovmd4UIsoK6i0/LjMPqPyYv7YASvsHj7eXWqkMsgJZDbCUJ4wSK1QUkj+m7JoEQ3pdUh+pkmBhQGQdJF9dyvmYYeau731Uj7e5C9nrlTjuiHfKQiCdnB1LrT05MgI8i67hd8WY6OGsp6jonZBOsVUinygfwfv0nuI3AxmyPRKuK5FTA62Zlt9lOsNGWU4G0j6iowaC6An7jk6LTe3yBXM+0sy6icsybFpYVhJpGu1ul1JSKe6eHDrQ46sAY6V/34c806b0j28O03tGZy+EO7tOmB40CIgVF+J3S68xofRYw==
    secret_key: AgAT2o1ARz6ObsvMn0Y8yFwmV2S9ahvtYV5SaCRLjcP6BufrntRvtL2KL6dSTU8TiwrNdkA2EU5o0thoVXQp2BJL6VY4kRTZSE+OAFZhei75CdwbqLX+vAgYfFKIS7KwFqLqFed1hu6ykdkDweKF8TgzbUdbZFn5Loq63mB5w/HjyKoKfZ2bcI/zMfSOW10CkAuiiqaRj69a0D8LWSBXSJ17n66ePR9JEW9F6eWndbxkx8ZBbMAIPT4K36IdhVKZ1dfMScY2YYERZiNNSzZ3VHKvlJ/PvZ+ycFuFhsHc0yJwW5Yac8MWJWpJrrhHagCiUFRv/mPsNq9mNs4KGMjP2IYceOy3IWkYSR9hCaeERWlfxhEeTbBMKwnWSYKjoU+jyoyhT/i2rJL6PKUt2zfXpFr/z13EuYYBKxetuSQLXuPw7chc0h4830EXsrmVa6KL4iyBpqd+cRaYH4fl96rjdPsvbsb2WV7PW9fQvIwLlGZk3SnOZIAfUz9QRqsPxfQFh+Tw3TNX5fWAsQGsNEAtjGrs+vudTWqGotV4/mk2esryZ5XzsikbQehA15BYtty0rIaqvorTj9nTObJ5Rh6vgQpIPYNp6SekhAdbbFiEIObFwmY8hR0R2VgxVXwwhNEZs5l6Bx6Uq3N1caA10MS8ZhP/2iWnx2oyHiE85+q/HgEbOOg0BBV2ow6pRO5VBI8rBA59mProACdoia1JzoL/rDyLtryWRC7pgckyXVh2hWu5in70O7Tjb580
  template:
    metadata:
      name: mimir-secrets
      namespace: monitoring
