---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mimir-secrets
  namespace: monitoring
spec:
  encryptedData:
    access_key: AgADrBfPRiVVwvq0eFRGS+0DfQ/pjdh7Wa5zL51ZYppbkcVJOWolZSgE11Prtg9IqkWsr1ffcawid6+qT2KKpQLHwOXRPvqUfK0rmb8doxFnXKNJQ/gyqw94lDqq4gnP1xbv8AhhLgrioEgn242UVLs/Y8nutcdb0oCsUMqTlBp+frYtNLSwryWN0xM3Aisczs5kmv3ryNBaKYlLS0YbAaz7Q+hryzIEcrFRYvlTGbPImrP/tJ9mb0k5wwFiw6micSQywr8dNkAmx8o4Kpk19O5B7Q+hkjrtppccFidgUjBJE9idziJAWAfqeVbqg2NJVD6K7pRouefdBkPJ4zPawtPtp/rdYlLWsIF1VqUOmGpquzqDOjfpLdrG4KjJb8QSMAa0z1r9K1QvbFbJI0JXgMTxubBEjZNaQXvK44YV07jI1is3r3DKfNpzPnIF4dwARm4ijMTueiobLf/gMf6o2sVnCltJghq2NijRUcudVIFWq6Df5cjhikJmoKSlouvLLUryqsq0jNLtfdQ2QHbts6uTONzKGV2umP7MI0xEhd/Zi962UjfGjaeC+VMgnitGtv0RWu8pnVqWvRhsRO+JjDv8/nzcf97KDaQV8kTgdEZlKCzKNorfimcfPerDZM8lTVObW6ZhYzSuC7gSVzDhSC0NT+C/LcHTzPiZrDvOa5JzF5X7+dkd+hr+8GOSOheSAzTRVH08T0PeHFSxBLfar66kpigbhQ==
    secret_key: AgAdI+FxjkRGPC9SBwctDk7jGtuy3Wu5dM5WQkLPopjqxEYSMbVwgT9upenopKw09sProy4iPCueTB8JsHIZ9eeBNFr5TSokbuBAWWYeNia7MLxKoy3NIxKlb6GORAch+Db6wvrgvx4SDnW7hE0XlMqA7Kk+m4qo+AHbrEvqewgy1jiNOOfnhNu+GBUrmVuROKdoe9dU25uigziOwvcFcByvVypbCAfqC2hEinbFqfPjh6AjF97XEe1jTUmKzMe8WuqjlYnfNYMJ+0YzYCXarr1yt6Ta+baorY/zlrbtLzA8MwoL4hFx9UNV6rLZWD7ZcHoLI2H2WP8UCqPX/yfebX/RRQubnASyHHAwVhFm3HHfBTZoh8O7ByoiygRvNM3GlTEyYfkU2eExiadTSs5pAuZcwwi9NpyVADx2sH7Sehc3SwLW8wuYhkQ6PxR+8lon9R7imaSOabVxi4CY9zy1gy+RpzGtcTdC7LYYEuzxAj22guRhIhquopnlpPo+ug7HSSSwjTWVOtSZBGHvpzkwIwxTaWMziTgzBKjIaTUqBpfXUyJ1Hi9WlNxXKXdyerGAL+DrmScEG2MGMJkXcaYLxWoTDWC+C7OWOkamGPI4r6MPJSK8AxKlZafkvHT9UBTbsD+vYpJjk4Au1JrcttPudlCKROMJ7HVLDNJXX6+MJ0UCajGsHWhwBbs3BelvGVg2ANcL98uaox1NbxQMyDHXMH9DWy34VmsT2D9nBlkuS1/wsf79opj9rlqN
  template:
    metadata:
      name: mimir-secrets
      namespace: monitoring
