apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_RENDERING_RENDERER_TOKEN: AgA6NlDrXDdH/JASnjVZsmZlRaEyvq9O/y4hpMW2AEVIqNyrYHhDJxbH0xQ+SqRIKuof6iX/tNxT4t7RbQ1AbzJDQgzWjAwGCMymJB31pSBiYsmr9+Z4jYQ8LHjS3JJP7+SeeXPvqNv/5QvwFsIvhwWtU46r3NYhQI+vP6WBv4ObwFgw3G/9hkIvTlPKwBPZ98cSh40fw7ZRTvOSIqDIPjqGA3nmHV5rO307sCjyJ7DCFGgIUAwM6qkZhAbmyn79BSvX1aYjb5vEPv91Nlx05E78o7rJlDcdlJ00Zdt/4oOJiMlgdZWqX8LshYJ19dBlFXi48v+lsYE2MpG7ePXh8JrA3DmHFfh0ad87IUlgt7+x5EZntdD6LiEAjXOSBCNI4g9mqgEJfJ6lolXgw1lHkmI/duoQDx6GnSWwfbqnpKAaurB30xcsMdQwZPeBifrsNLDcn+Moys9xHBr7NKuo+ntqji8S+OrN23LZV2LjXGZUHuPQCTGcZZGrMvnlW6Oa4D1a6U+umMBemOXzNIJtH9z6sohvAt3zJ+9Fvpc2bQsy0hGuL7JmcR+cNaKxW7yHeu2p8OR/7A/lcQx4C9Nmm7ejmUVo6/HIGgSlEfSfs6bX69qJqZkJwSWXGuNCZy1OzLNLkrE0/wH50RaGDhLrI0DD0B7DxqKyAU+aKzyvKzNDSX4eoBtHAdgoReSn/ITWA7xNa/TcdR8VfYg/icxFWiVd
  template:
    metadata:
      name: monitoring-secret
      namespace: monitoring
