---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-secrets
  namespace: monitoring
spec:
  encryptedData:
    access_key: AgB/ADCUv+RoWqLmaAu4/Qin0w6iyd+eOJlA7teqn+Wzg339p7cNJClFAWnD6164I8fXYqnaeRBNut3GjNIlr96cqsmD6/IpTFtF2JZUws/4JL9495nks8zQIfaogcOilChq5d1iXR9S+am7KSrW5E17eQ3d+XX5IcWj+W0GeDZtVdMB4mthJRkDi3Z/8vFPWEMTR2whNK2PygoCNZx4JqDPeOcwp0Imp02W5pBzODvb+8xYF/Cy30ctYJZY+ay8xXJoSdQJNrC2L13V+dTpWNWsoQA+T7U8qm7udrVacVhpg9eVODKonycBmVyfY1ED/zvUnkxRIWq1yRHw/2kx4FKdzUl6YuZDnYT252r4NLelveKufGBWDfSkpnk8vXhn7ffz3DWjPgiGNq8wFQL9BxtmIttmdkxxtFF79DVqE3hycl9F76Z08MeexEohMeNRKQmH6AVKgSwCaw/qyx+WAN5QyS4bxqtkM5PJ3XbbnPf8VqCv31HWmiDRqsHic2t8aEB79Y4psmyoxq/Ik/XcquXCotgaRLi2uZEHPHoaYZBiWshORkKX6AdkGsgNOocltO6sZHPp3f+nF9zaj+HiC70Fztjp5cEBWeTCF+6KDTeNGD+mHOA1gFEVgImiNpeZhNRw0SdtpiDjOGmCcLeHONZbGrRyCQ5+joaTbsBbul4KAuXOnDRZ7yMmA4O6CMNxkhtHottfBTT4n2eqhCN9XZ2laq9amQ==
    secret_key: AgBHDSZB8CZMnHqN6Ad4BomGxS8UYG/u548961Qep9SjyidZXP9fUCaaW2GmZ0Q3WgDFvvHxqkIB5nCK3+2tSgoy3XzXBupwd8MFMdts2N8EhiAiNe7BWZ9iYihqYKG2ZRf2Z0QTVPYOBbLLDX7o3fwbkATRfhLpvEPclbB6dw7S05M54LUKebS77RYTKHYPO6B9Zd6hmBRcPi92EHV5hr3sNhPApIcrfSDnaEL8uqapxxTCnivakqX22YcEaITj1AlXYuCMc6H1beICEOoqCdr2j0px53ncEAFEtIM4OmcxkW9aAkSN8pu1svt7j6RGWZwU8hN4P7bzOH7vPQKCgFQkwTNisEElLPq8GwyWCVG/2kQX/jOMHgjsnKBWwdfKoLxDN+X6/BqX2xytVznd8ujQhfnk0JsqEJVh9S4tt/0B+lTeyb2e7DmuJCpUZAYVm9VzvyYSP1O4HHmMcvxgJ1luxB+6y5lFnk2vr4w1qdB6W3goJl8UZRIM4lw9m84asbBkQRftwpDDVz3kHEjKfBTp9sMxkQr6CYfRnyyL8o1NRa0wby4JTY5i3kul1nB3gpi+sHPNz738PO1lCAP9mt9HVu8nOvk+bs7ueFQPdhKan6urTd+ZwaR0ElGZC8Wfj0rJ8OE4ZBxAM6l3yMsaUz2ZBAWRF3NGVH5IOZrgsTbqr33Ze4/v4h9KEXxJN/nJxeX0EdgD2bPrSG8/unE7ynGDKzTg+6clQoJmeMRfERSvztGwsHzKOlfE
  template:
    metadata:
      name: thanos-secrets
      namespace: monitoring
