apiVersion: apps/v1
kind: Deployment
metadata:
  name: welplan
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: welplan
  template:
    metadata:
      labels:
        app: welplan
    spec:
      containers:
        - name: welplan
          image: ghcr.io/pmh-only/welplan2:latest
          env:
            - name: ORIGIN
              value: https://welplan.pmh.codes
            - name: WELPLAN_VERBOSE_LOGS
              value: '1'
            - name: WELSTORY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: welplan-secret
                  key: WELSTORY_USERNAME
            - name: WELSTORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: welplan-secret
                  key: WELSTORY_PASSWORD
            - name: DB_PATH
              value: /data/cache.db
            - name: PGHOST
              value: pgsql-service.database.svc.cluster.local
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: welplan
            - name: PGUSER
              value: welplan
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: welplan-secret
                  key: PGPASSWORD
            - name: ADMIN_OIDC_DISCOVERY_URL
              value: https://auth.pmh.codes/application/o/welplan/.well-known/openid-configuration
            - name: ADMIN_OIDC_SCOPES
              value: openid profile email
            - name: ADMIN_OIDC_ISSUER_URL
              value: https://auth.pmh.codes/application/o/welplan/
            - name: ADMIN_OIDC_CLIENT_ID
              value: oFx8CL9kOoONKQW7hzMem9c4IN2dYkJ1alN1ihHK
            - name: ADMIN_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: welplan-secret
                  key: ADMIN_OIDC_CLIENT_SECRET
          volumeMounts:
            - mountPath: /data
              name: persistent
      volumes:
        - name: persistent
          persistentVolumeClaim:
            claimName: welplan-pvc
