apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: welplan
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
images:
  - name: ghcr.io/pmh-only/welplan2
    newTag: latest
    digest: sha256:f93c6b61e6e8b8afb260a30e35d0b19d2601426861b62aa8088e864e8efb4ffd
