apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: welplan
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
images:
  - name: ghcr.io/pmh-only/welplan2
    newTag: latest
    digest: sha256:60a985b1110b0613b933ade1b022a8adccfaaced905720116f11b718d0a803d2
