apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: welplan
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
images:
  - name: ghcr.io/pmh-only/welplan2
    newTag: latest
    digest: sha256:da0b63ee122eb7598defb18d1b48b576c28a9c43f4a9777eed76230b216b1ca8
