apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nameserver
resources:
  - ./daemonset.yml
  - ./service.yml
  - ./ingress.yml
  - ./certificate.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/technitium
    newTag: latest
    digest: sha256:d235b6f5de1094fd1c99a431b1e4cb42a88dea1eacca0e42806d6b5cac091848
