apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nameserver
resources:
  - ./daemonset.yml
  - ./service.yml
  - ./ingress.yml
  - ./certificate.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/technitium
    newTag: latest
    digest: sha256:ebdea9bd1774e5c30367861a8ad89ae8e8a6c47fa3dc4c5b86397cec1592ffaf
