apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nameserver
resources:
  - ./daemonset.yml
  - ./service.yml
  - ./ingress.yml
  - ./certificate.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/technitium
    newTag: latest
    digest: sha256:752e836a371cd58eb88704a56bfc0482d55e1cf3672e901e2da239ebed3d0762
