---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nameserver-tls-keystore
  namespace: nameserver
spec:
  encryptedData:
    password: AgCORoQ3ZGExRAsfk4iOLd/M/vTEbjTpx0IZCwhPYM1wx+7oFg9Aq7LF9vVDqOXwfLSk8IuKR2nTr+PF0bs5d658Axm1ci3Nlr7EQxljICBqlZ7CkvafRMsgQRx+BLCjF0xKpaY6umKJbf+0kxmafzn7CWlwrlGbDzVIWuhiy4+u5N54kvrJctSB2FYLWKgMI1uap3xG/SS8UMzAnkRtnhM47kuSrqy143oUqvCXfsSrJgvGPEJV6xmkbKyIwi4UfzegZCgG+6+sJX8aeINv1XdZxbfEUwKP4RDcSO7YF2hX/6vHL8WxV4OCYYrrttMfIr5Jfb0Yx05hMFzhxwe+9/1tLRXo+WumsZtRQtAdagJcd0yXxliuMHB/5ogMVH8wDkLdP3SMdOG9MEj4pPQGbbGih960KQViWEUwiF8/wbKtGSfAf5NWaelIX3xlw/kH/DUjTrO3XsexoJQIrhaFw7h648R5Usw3j8qOWRtkK+CMVzfF3E+erOITtXKVQ/ClHKwToENf2tKjXY//rqPn4SEmyI1Zid8+kRyOhnoXE4Hp3ajj+9wAyDr1/yak//VT50P9sWgHAXd6FAgiZDXtsZpRZFFk51kfimxGlvX4/82pSXddpwwfKQScOdDM9yAdKrs8xO7LrcHBPMdCdjgmWR4HDJGNrYGqZawVJybEaNGP6GalOh++HhXNl5Lo+wGiivbaBdKW6GQxT+iz9qBsfSNo
  template:
    metadata:
      name: nameserver-tls-keystore
      namespace: nameserver
    type: Opaque
