apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: track
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
images:
  - name: ghcr.io/pmh-only/dawarich
    newTag: latest
    digest: sha256:d6117073b5312ce372b1e20d4fd5bf6c83e2197a9b1f51fd181dc0f0eeb8ba2b
  - name: ghcr.io/pmh-only/postgis
    newTag: 17-3.5-alpine
    digest: sha256:f06c82972bf96351d8737f08c4330c5a55b5732a120915a2a6f79ca77e34963f
  - name: ghcr.io/pmh-only/redis
    newTag: alpine
    digest: sha256:42447a15c58ed2014f8b9ed5573488331bcc9f409043b16cf6d954a6b4a36590
