apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: track
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
images:
  - name: ghcr.io/pmh-only/dawarich
    newTag: latest
    digest: sha256:b2a8e1b29ca7dbf403fd105d2cebe9dfa786f4accc6dd84ce8e280863071f5b1
  - name: ghcr.io/pmh-only/postgis
    newTag: 17-3.5-alpine
    digest: sha256:f06c82972bf96351d8737f08c4330c5a55b5732a120915a2a6f79ca77e34963f
  - name: ghcr.io/pmh-only/redis
    newTag: alpine
    digest: sha256:ae2f4fe8a9b9f162e228471b4ef55603a2699180780247cb682dad54a9b0286f
