apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: track
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
images:
  - name: ghcr.io/pmh-only/dawarich
    newTag: latest
    digest: sha256:5c3d31527fdb6e12996502ee72d0f0c37295f92b89a42678712e797b18b3e7d3
  - name: ghcr.io/pmh-only/postgis
    newTag: 17-3.5-alpine
    digest: sha256:260f074800af0c1eca83330e5e9e97b9faee64721b9540924e231006fa76e7a8
  - name: ghcr.io/pmh-only/redis
    newTag: alpine
    digest: sha256:42447a15c58ed2014f8b9ed5573488331bcc9f409043b16cf6d954a6b4a36590
