---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: track-secret
  namespace: track
spec:
  encryptedData:
    DATABASE_PASSWORD: AgCKXHP10VXfv49g7FPSRAkg0YdXa5qFHA090EgHJrOqSwxpXa7CqKF21ir/nX9Iam5MGoJbv11NOooJFdz0BNzPlfdKRwVDm/LE8XmHvL1rCl8Y8C32C370UB2ejBQbWNsSN0hcJbPHRx+dxUEqyoOIfirG2IePiFqgYEY0OstX/lGmuyyzoj9RMFHQR0dXS6U2TCKeS6YUqf7GsR4afnTaa7LHGkfgZc4HORcYUc4srYhYugD4YYpP8jAZa+nGCZ6ZBD8AlPTqIISr1UfXdYOBvcYhpNY1G5EcV8i55oUzeTlCFP4uyNZbcwgH4mW+c40VkfCUqz6Qrg9iuvG2eLrdcHYOYIJJSt+nusNfN0zEVXtYgakSC9dcRojhHXx1XI9osfrxqiFSyRjAuGcV6OARpKdXV37z2mfu/Euhi7agPoCHJPPo4cr2zjT0KOAnAKq2PHji7/KTCt7sv5GQfTl40N0N0z0MP11mkRT1dcb0vRFGV3vTX2aHQg5YLMRDwfl5RL/ks0nuFL8U2n4mQ4NmNqeOQBMw0vboLaWf1Q/pC69ybhH6BRQQ4Ea54M3S+EZv+T5PD6Pf+tR73KGtdQWpmWeW5rNbUiNBvA2qg30bkMB0mpCGpNf9URWym620QbXan9lCZwQEa7DzlzsyyS6C169O5gEXsm79HK5jJ4bpL2RywAxCGoafuo17kIxga6a45KNWm4C6oIc9+Af8mhnz
    SECRET_KEY_BASE: AgA7KAlpVC+RG6g35ke2OpGWWC18WWoaQhS1Gu75t/kgIdYU+detUP4IWGUWvSSBZaCyl4mQKYSeEZ/yyFK5vUT2LY8Foke80y9qUQGr5jjZAQsppLUgXYf1OTRP6a4R7Um5dsA0+J5bwuY7unUtq3Y9P+qGpHWdjU+abGrY3/mrdBP+rsOr/g+/LDjL5uhXrXmZ7D4WkamfTQbTiFRSZDFBmDF/hD3oeqreX67S9sellHbbOv40B68gu6jdFYBPDgJTziL7ON6yALweIuuPQcNEVNnSktMjTEBuXHvaIS25U9T4TCo0f1VbDGBjgA9og2AbpNtoFSuf3ANu4bkMv9cQwbJHCw6sD9jnIGfRDQevp7MIvInH8WHWF5AKiFvqaknl/ROH6xRXJZM0339Mlx9nYDlsdTjaRJmL5FjF7HuOw9sx2pV/xymLtMuolAZM7lGYb2aiHDDsm3x7jBLsDuL7IpAFYEWXO/sB6iT2BNRTYuqkfyiiMDf3biPlA+6uOEakBa0+H1iaDPBbaVoSa0AjbGypmCJJSr8nfTyfotutxzr1MAiNYm4u03lYnHNnpDGZ5c0CiO6nqUAgyjI20U520SOsvJSFiuSDdC0zTgUIiAVzm1vYIlklDOBbdVkD55il2Gx4rSp+HEGpOOOT80G4K9EzSmBpBqM1wSj1p3mOZvH7LrBVGG2NlDoMoe7Y/MxHfXnowoUy3irI2nxBIFHVIS5TZFjl3h66Dv8HX6yJYC6lz4VisW6uM5vQqy6C8TYc8h8dT3J0JiQf/WrqJh+BKZRg54nyo5w/ClLe/ipKtjJtmD44xnhCF69H47ZP2QvfV2lpwlNNUn0XXgUPUhDQB1LH8R2kxeyudbVNbVqKgQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: track
      name: track-secret
      namespace: track
    type: Opaque
