apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./backpack.yml
  - ./mysql/pvc.yml
  - ./mysql/deployment.yml
  - ./mysql/secret.yml
  - ./mysql/service.yml
  - ./pgsql/pvc.yml
  - ./pgsql/deployment.yml
  - ./pgsql/secret.yml
  - ./pgsql/service.yml
  - ./clickhouse/pvc.yml
  - ./clickhouse/deployment.yml
  - ./clickhouse/secret.yml
  - ./clickhouse/service.yml
  - ./mongo/pvc.yml
  - ./mongo/deployment.yml
  - ./mongo/service.yml
  - ./redis/deployment.yml
  - ./redis/service.yml
images:
  - name: ghcr.io/pmh-only/clickhouse-server
    newTag: rybbit
    digest: sha256:9b02d0299f4ca98dd64a28594c2e9ee4a107b5d7431ee67f9f6375cd84fc04a9
  - name: ghcr.io/pmh-only/redis
    newTag: alpine
    digest: sha256:042266b1a5ceb2306c7524fc9e19d75359ad5644e2e5688f9e31317f2cf241ba
  - name: ghcr.io/pmh-only/mongo
    newTag: latest
    digest: sha256:04f0f1d5268d9e6872b64793d4d3463cdcfbeaf6bcf17dd73f25541a533a5845
  - name: ghcr.io/pmh-only/mysql
    newTag: "8"
    digest: sha256:83fdb6364293713cdb0c3a4b802ef6741142a04a33185d70ed478f24b6cf88ac
  - name: ghcr.io/immich-app/postgres
    newTag: 14-vectorchord0.4.3-pgvectors0.2.0
    digest: sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
  - name: ghcr.io/pmh-only/backpack-mysql2s3
    newTag: latest
    digest: sha256:fc4b02e57a8849967ddae35b3329b6d540ed144c83aea00c01e5dc860ac29582
  - name: ghcr.io/pmh-only/backpack-pgsql2s3
    newTag: latest
    digest: sha256:907d8a4180e0be87d01c20640b70e688f937dab3ba18b33f76602f3900001f32
  - name: ghcr.io/pmh-only/backpack-mongo2s3
    newTag: latest
    digest: sha256:abca64f5084b873d7752485bc32a694ce4bc6e4ce42088cb52164924ef3c8779
  - name: ghcr.io/pmh-only/backpack-clickhouse2s3
    newTag: latest
    digest: sha256:3a9989a87e30e5007389c40613bf3b10e8335ad8bbae3fc70b19a8abd508a538
