apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./backpack.yml
  - ./mysql/pvc.yml
  - ./mysql/deployment.yml
  - ./mysql/secret.yml
  - ./mysql/service.yml
  - ./pgsql/pvc.yml
  - ./pgsql/deployment.yml
  - ./pgsql/secret.yml
  - ./pgsql/service.yml
  - ./clickhouse/pvc.yml
  - ./clickhouse/deployment.yml
  - ./clickhouse/secret.yml
  - ./clickhouse/service.yml
  - ./mongo/pvc.yml
  - ./mongo/deployment.yml
  - ./mongo/service.yml
  - ./redis/deployment.yml
  - ./redis/service.yml
images:
  - name: ghcr.io/pmh-only/clickhouse-server
    newTag: rybbit
    digest: sha256:9b02d0299f4ca98dd64a28594c2e9ee4a107b5d7431ee67f9f6375cd84fc04a9
  - name: ghcr.io/pmh-only/redis
    newTag: alpine
    digest: sha256:042266b1a5ceb2306c7524fc9e19d75359ad5644e2e5688f9e31317f2cf241ba
  - name: ghcr.io/pmh-only/mongo
    newTag: latest
    digest: sha256:04f0f1d5268d9e6872b64793d4d3463cdcfbeaf6bcf17dd73f25541a533a5845
  - name: ghcr.io/pmh-only/mysql
    newTag: "8"
    digest: sha256:83fdb6364293713cdb0c3a4b802ef6741142a04a33185d70ed478f24b6cf88ac
