apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
images:
  - name: ghcr.io/immich-app/immich-server
    newTag: release
    digest: sha256:b434cb9287eea1471c9974845914d4dd328c9c2d652e446ed4930f99944f0ceb
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: release
    digest: sha256:5a0839dc5303cd7215bcd2180a26aed3af41675aefb3e75e5157e9f10ad16e6e
