apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
  - ./pvc.yml
images:
  - name: ghcr.io/immich-app/immich-server
    newTag: release
    digest: sha256:d317916b28090c33eb36b308464ea391f8b7df1d850fcfea227a39ec879718c2
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: release
    digest: sha256:e16c2f166a8174901959fdf85e2e4c7bd1ebc4b37e0b6655de97c41408a260c4
