apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workflows
resources:
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
  - ./pvc.yml
  - ./secret.yml
images:
  - name: ghcr.io/n8n-io/n8n
    newTag: latest
    digest: sha256:fba14bfeb4641d9d32675cabe38439581105a66ebd33008bb4a1522670a61716
