apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workflows
resources:
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
  - ./pvc.yml
  - ./secret.yml
images:
  - name: ghcr.io/n8n-io/n8n
    newTag: latest
    digest: sha256:31375a4f730081a139bba2d379bf2efaa8e662cc9e131d12bb5e15859d4f0282
