---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workflows-secret
  namespace: workflows
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgALFCBh7yrX02y9VsRbVDswPAEnHsZvxkFAdkDsr3eufPwvNmxI9f32glCBcKm2YLbrv4EYjSiKTBvhfu25lGvUrQ9Ohp6h0UpvJghNT1DhPYIsczUq3P3ZiFK+xuJqIZ66ineibNd2HhSOFUN9ObVUtIcV4Jn3b07soqr5X3vxWd2J6o9xXDUPVXoPu1ElSpfNMMdrZnPtL7TnXx9IT10UNRxXY2BBr40XhJsiC+OVEJ2/2csIvF7g84NJ3/A81EalMGnAN8IAbzvp/lOU63j+JX+j5TsHduJm250rfYMvKadkYbLi1sti6pX/+onaTYDEbQVbmVzzVXVD1o7NXAuxVw2IUqCR75FhdF7QYfps5HQYkxR76N6PnUbcpQbTnaD/EdiUw62O+Y6isWiScoUpL4cvvdq3aYuwrCNy1qkGXmLECcyoDxmd1V0q3S25JkgUsP89fJjETCq0V1y2nvtJDaqArN6z8QcnTTDsKgsc9g/Dx76nGDnsIBRfgZLhmvkAY02NZzd6hFWSXbzFDtoiT09O8iVZlZyv9HSVwkxxeLzmoNw1/MJDnDgv4rcN2gZj4Wa1qMvYWe0/+4rW8P1axPgxN8Ix652WGY8zER2LgpjBX2CdobupGO1LQ5jcpaUPYjQaVbijGiXyZ/LNwFiVeaLPXrnbCGY+JWBg0SuPQDRyKUcHc0IlaWYm8bmxxNM0y/xXV/SBMWVdkqNzKUP1JO7CQVjTffmxIOkEESszmlgmeB6srvdP0o5HGnWh1aom9kbJx0jLI8Of9rFEDRcRQtL3EZaX5XDa5xesq66E9Wvau98JNyTdgrERF/hN3slXXsP1qubJB3q8mxqu2HlFkOv2MryzyHjkv74BgcoUmA==
  template:
    metadata:
      name: workflows-secret
      namespace: workflows
    type: Opaque
