apiVersion: v1
kind: Service
metadata:
  name: gre-gateway
  namespace: as218822
spec:
  publishNotReadyAddresses: true
  selector:
    app: bird-gre-gateway
  ports:
    - name: wireguard
      protocol: UDP
      port: 51821
      targetPort: 51821
