---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bird-dotenvx
  namespace: as218822
spec:
  encryptedData:
    DOTENV_PRIVATE_KEY: AgBmQNsih9+hzBM5WNhjSPCGkU0VTmtbLR1utYMhMXkwyz9Jme6eaX5Mpl5HfHUAaZYqA3QFrMvsI5RR6C7drksoTOgb33LAcn+QoOCzTn5WfyNt3pmcnpkF35Ci+gRNp0MKcoIE/A+VGo71DzIvqC5sGxYw6Nam0TQYZsMjIREkPsCKF1y0onh+yxUXmvPxHKPaJVnkTegc3r5nQ5AyXDyIJNrH71+OFTxw0JOV6kMKk3AaEw/5FxYjHwmbITWnS5idb8GiKh6Ld3X6dfDzOuYsYrgxiN+xRqYwijfTYLH6Nr3POaVfkDes0x0kada7uLoJ6KYl1YcdQyAJM0sIxGEE8Tk8BLPocGnf3N0adlseyfmhKi03XxTR90OPQ0o/KN0MIpRclsy+6k6tx45ioupDTwKmooodIaTnfAwQmWwWhb+FoIpCLteUtPcDnwHjBDd0HyteT8efKbZMY6aqhMHkAyAnbyrmSOX3iqTU2BRuVOPafqqLA6kmBJAMWWEHMmAcZVLPMFbDyWAhae9O9xn5+3iXG81SFay+Z686x/MsDAUTkZ0ITDx3ICuWSAN8Y5GXbWU7mZuMD66Gh0zeuVPe9fkBCqKk5STlAckeGYP0oJvbuFopwhnwpnC+kZ48OvV1UiRwUjfXVDhyOiG/+1EW4N9grLXBIfGCrvA9zfvwWjQdZNDCtanNJCsAUXM01CXJN+lr0HXOWTf4wL83JK5wSMTvDY5l/kEYeUIysmVGuuMHG3hesMzIvOKjBeHNUSycswuqYHkHiWeN1y9adBl7
  template:
    metadata:
      name: bird-dotenvx
      namespace: as218822
    type: Opaque
