---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bird-dotenvx
  namespace: as218822
spec:
  encryptedData:
    DOTENV_PRIVATE_KEY: AgBx2tHXvqh61jWQUkNw2aJYvEozDcYu2DSQb3mfw86d9Ndhan1WFSK0Er9dIYx/PpmkcusOyc1rYnq+DiO8ejiLa9awffaVdS+E5ic8gyeGwnSgiKv7itcNHCsy3im4Y0k0EDrEIxuhv0gq5q/knx7dfEopq5lrh2JzZSvYB7D5/3okCp4gMwT7ur2kq5RkkQYsi4Oqqw1dCRHMjLvi04ZON73k3glmVcri1ciDJP6tuUpaV1H0FhLXFEGJYSa5nlkgz5x2gtLtTF09xMfgeqHPDROyZ8TokFkVvLYzGRDwAHDlKZgh8m9F2dRGgTJi+cPAkd/fJWQIlAgHdWK1XVjyCwnQ/cVOchPWwfwHIKgfAqqm5eOucUKutGs55PD5E+hPVLXI4PauSRWOkAP1Z+S9tcHmwI4KP/2pX6QzvBWtNWX73ILEm1N80uPmzQh0KTrRpm0tbUlrfLBYVoUBJXVPv/1ScBUVR6yD4gTw3ZVnhfvkkV65sfD5yGMdWWLax+kSQ+6Dm3dUblFVM0mixuEt3TM/DBvGY7diUGWdURw3QVBMuZU4Db+1B9+GH/Qdg/0Uk0xL/cIn3HO3NbP3z0OHAFWx7anrAqUlCyNUkl3tdtopEkcYZxaCw8veOl1uKjwxxka+B3Cdzh7d0VgynifZsFAU3gSvSQm9S8F1bTO4bY9/T+LSYidd7iMMVEsHt4qXsQGZPhezFhL91ityCNptVOLzvuoIbgKi8j4B6ddE7l/RfddfisLyXvrqf1PUTWYqIds0C+HaPy2+6aVkV4z2
  template:
    metadata:
      name: bird-dotenvx
      namespace: as218822
    type: Opaque
