---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard-portal-key
  namespace: as218822
spec:
  encryptedData:
    WG_PORTAL_PRIVATE_KEY: AgDTCD4Tvua9737fpj8wQGUgrAFVxR53LdgSKhM0MJMzOsjgvl75sOCLmyNMf7wcf0b0R/kDqrL0zhiZkcSUU6Rlzt8Y36tmrNNaufbFx7v9SER2+B/hSriMjzXslVEYlslDAm4SHE4/OnaipM1yrpxD7/PorulvaHdVxnH2LiaUcN88L+K32kV9u4VxRI7oxGyRpSblOcIJ2M5dko53cAL/Gnb4CRHfbNFVLnpyPNb5mEziY42lvixMIyrv4bzeqqRwyMhaV7nZyb89cA1704VboY8W5pA/614smaHw/bAlaQEogYgx4AXPMPrkY9v0xb1Wn8i3/LX/6YEx2tJO+Pmpr+n39Ygntrsc23mdElU8cA+siFKiXOJ99g4MCgE24vUJACF1JL1Pmm4iqabPmFr3YELTYApQosa1Jow56wo+OB3Y9If1vUGzHIy3okVGeRAqSicNZirVNcsq6Nuz/wvYaSmPIIPDA9MjXgbbY7GBLlp+ZhgkcMzcIEj/9x/Y/lDZaoFrGPQFHHgqgc8LKAEU4w36Ppky3uZmLOb6Xhtr/85UFSGYLPWBl4+KrRVL2eanyqofjkwc4j8d2sg4w0qNcmLwvrKcqE7Ydj0VtsLHiuXinD/qrlvrjhxg06ynclOUBx3ZJJ304lrSpEluGslxvM5XfdrcvsRS7L6UfG4kGNhNnEX0PFB2eizAeTORbsjPQ0Q0bNxpQmmBp4F+hwfj+21IGdlF8IbF31veHmV5GtJM3DyE9hV63gd2iL0=
  template:
    metadata:
      name: wireguard-portal-key
      namespace: as218822
