apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: connect
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
        - name: connect
          image: ghcr.io/pmh-only/connect:latest
          ports:
            - containerPort: 80
          env:
            - name: OIDC_ISSUER_URL
              value: https://auth.pmh.codes/application/o/connect/
            - name: OIDC_CLIENT_ID
              value: wA1ypwpdd0ilNF9jNJSahpQeWAyViZ0ucbhx9aPm
            - name: OIDC_REDIRECT_URL
              value: https://connect.pmh.codes/oidc/callback
            - name: COLLECT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: connect-secrets
                  key: COLLECT_TOKEN
            - name: MCP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: connect-secrets
                  key: MCP_TOKEN
            - name: ROSTACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: connect-secrets
                  key: ROSTACK_TOKEN
            - name: ROSTACK_BASE_URL
              value: https://connect.pmh.codes
            - name: ROSTACK_API_VERSION
              value: 2026-08-13
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: connect-secrets
                  key: OIDC_CLIENT_SECRET
          volumeMounts:
            - mountPath: /data
              name: connect-storage
      volumes:
        - name: connect-storage
          persistentVolumeClaim:
            claimName: connect-pvc
