apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: connect
resources:
  - ./pvc.yml
  - ./deployment.yml
  - ./secret.yml
  - ./service.yml
  - ./ingress.yml
images:
  - name: ghcr.io/pmh-only/connect
    newTag: latest
    digest: sha256:8e9aa0904926229d936e3e044a44a4e0b742fe76ac0b6f8931b3ce5c2c8396b4
