apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: connect
resources:
  - ./pvc.yml
  - ./deployment.yml
  - ./secret.yml
  - ./service.yml
  - ./ingress.yml
images:
  - name: ghcr.io/pmh-only/connect
    newTag: latest
    digest: sha256:01cc28d86a9325d1457708b54d88ea818f6df4d3ba73950ff21c932e705e6c56
