apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: connect
resources:
  - ./pvc.yml
  - ./deployment.yml
  - ./secret.yml
  - ./service.yml
  - ./ingress.yml
images:
  - name: ghcr.io/pmh-only/connect
    newTag: latest
    digest: sha256:cef1841334e4266841d8ba90573ee354d85ae92737643a6f320cea12abdeb33f
