apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-upgrade-20261002-backup
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi
