apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: go
resources:
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
  - ./pvc.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/go
    newTag: latest
    digest: sha256:b1d536387a5fb6bcb9a7ac71e526bc9d40d98984b7f07767a67372d113c15e2f
