apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kopia
resources:
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
  - ./pvc.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/kopia
    newTag: latest
    digest: sha256:e190a22ef85f3d8446b22e6f49be5b38e72c3750b784245684c75ed9e87f63b3
