apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spotify
resources:
  - ./secret.yml
  - ./pvc.yml
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
images:
  - name: ghcr.io/yooooomi/your_spotify_server
    newTag: latest
    digest: sha256:624ea009f2ef9d877989bee9c7913ac66840449f566517871696c31a8ea13ddf
  - name: ghcr.io/pmh-only/playstats
    newTag: latest
    digest: sha256:201c5731f82012adae923096e23c7d397373e9b0acb9680c48cf1e05891656d9
