apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-guacd
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: remote-guacd
  template:
    metadata:
      labels:
        app: remote-guacd
    spec:
      containers:
        - name: remote-guacd
          image: ghcr.io/pmh-only/guacd:1.6.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-guacamole
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: remote-guacamole
  template:
    metadata:
      labels:
        app: remote-guacamole
    spec:
      containers:
        - name: remote-guacamole
          image: ghcr.io/pmh-only/guacamole:1.6.0
          env:
            - name: WEBAPP_CONTEXT
              value: ROOT
            - name: GUACD_HOSTNAME
              value: remote-guacd.remote.svc.cluster.local
            - name: REMOTE_IP_VALVE_ENABLED
              value: 'true'
            - name: POSTGRESQL_HOSTNAME
              value: pgsql-service.database.svc.cluster.local
            - name: POSTGRESQL_DATABASE
              value: guacamole
            - name: POSTGRESQL_USERNAME
              value: guacamole
            - name: OPENID_ENABLED
              value: 'true'
            - name: OPENID_AUTHORIZATION_ENDPOINT
              value: 'https://auth.pmh.codes/application/o/authorize/'
            - name: OPENID_JWKS_ENDPOINT
              value: 'https://auth.pmh.codes/application/o/remote/jwks/'
            - name: OPENID_ISSUER
              value: 'https://auth.pmh.codes/application/o/remote/'
            - name: OPENID_CLIENT_ID
              value: 'hrvPK2hBd17Ha9oPrCxbt0zg6tVpwHwAcVAz9Bii'
            - name: OPENID_REDIRECT_URI
              value: 'https://remote.pmh.codes'
            - name: EXTENSION_PRIORITY
              value: '*, openid'
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: remote-secret
                  key: POSTGRESQL_PASSWORD
