---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: remote-secret
  namespace: remote
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgA1nupQOIf9tAflX5NDXuihe5Rdfe8anmG4/FKbx31ls5tpeyOUpGoFTHqJfh0HXiiQWYs0+U+gn7HX1scVPJ19d2Vf9Iifj7Kb6Jr+0Pj+Jl415sRNottnsQAqIGS6+CZurNCle/pTYsGLCUkIwnpqRL5iuoWp1yk7KaejVoMCgbPTgcyiOb4ZsR0ehFeoZVFcwOY0sN2hRQkUl3SQjRzA8/BAV3niTzw1p5v/7hw2cd4blGdCMINz9T7Gjqgeq9UsRD+8TVFIJ3QrrcXqTn4d1+GU+sneshkknc2pQheaH4XmmWpwGUZbkC7kD97oA1+B4k+keLSAqI1dXL2If5K0DignbivJEHXWfs9eQhUlMSUwWxPRZ4yakm4YEStWm937d98lRCX3fO6zgzn0tSvTUCQMLJoTzv4l24gs2sjJO3BGyiVm88YSx2yFg6CJ5ucHlgkFyIWYPySfk21OSd/YiKlWOGTvwmsN0I++3/spbQFxptHWQxtztzwx1QJ3EAz/gI1udoO9Kh49tDjxRs4A1n3XuyNk2I8G5kiQ+UofMEsNmw/OIPoQ0ebnTj6rbpf/QrDhc5Oo0ZZswv6M3p5WVuyU2Q7vERYJ1qEsWqLmvlEW95r8b5BwEyrQK0KKeyPlSyuG1OdpNgzbZkaBpfVQ0xO19SQKjERINU7FK42qfVj6cB0WCUgIeJtNXFw5HAAO+TjN3K+BNlu/TIzOL/SPqH/g
  template:
    metadata:
      name: remote-secret
      namespace: remote
