apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visualized
resources:
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
  - ./rbac.yml
images:
  - name: ghcr.io/pmh-only/kube-universe
    newTag: latest
    digest: sha256:8bcb94d9606f2bf0d5f44f33dd052da3a04c49fa15df2537b9e9b21f27c39051
