apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visualized
resources:
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
  - ./rbac.yml
images:
  - name: ghcr.io/pmh-only/kube-universe
    newTag: latest
    digest: sha256:571bcfd53c4f0145b6c5958d28a1ea2a8e25d6229825709fc98f4f5946f82378
