apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: as218822
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: as218822
    server: https://kubernetes.default.svc
  project: default
  source:
    path: as218822
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: as218822
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/git"
    gitConfig:
      repository: git@github.com:pmh-only/lab.git
      branch: "main"
      writeBackTarget: "kustomization"
  applicationRefs:
    - namePattern: as218822
      images:
        - alias: ripe-atlas
          imageName: ghcr.io/pmh-only/as218822-ripe-atlas:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: as218822
          imageName: ghcr.io/pmh-only/as218822:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: gre-gateway
          imageName: ghcr.io/pmh-only/as218822-gre-gateway:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: looking-glass
          imageName: ghcr.io/pmh-only/as218822-looking-glass:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: tailscale
          imageName: ghcr.io/tailscale/tailscale:latest
          commonUpdateSettings:
            updateStrategy: digest
