apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: authentik
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: authentik
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/git"
  applicationRefs:
    - namePattern: authentik
      images:
        - alias: authentik
          imageName: ghcr.io/goauthentik/server
          commonUpdateSettings:
            updateStrategy: semver
            allowTags: regexp:^\d+\.\d+\.\d+$
