apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: books
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: books
    server: https://kubernetes.default.svc
  project: default
  source:
    path: books
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: books
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/git"
    gitConfig:
      repository: git@github.com:pmh-only/lab.git
      branch: "main"
      writeBackTarget: "kustomization"
  applicationRefs:
    - namePattern: books
      images:
        - alias: books-frontend
          imageName: ghcr.io/documentlane/doclane-frontend:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: books-backend
          imageName: ghcr.io/documentlane/doclane-backend:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: books-worker
          imageName: ghcr.io/documentlane/doclane-worker:latest
          commonUpdateSettings:
            updateStrategy: digest
