apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bot
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bot
    server: https://kubernetes.default.svc
  project: default
  source:
    path: bot
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: bot
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: bot
      images:
        - alias: bot
          imageName: ghcr.io/pmh-only/bot:latest
          commonUpdateSettings:
            updateStrategy: digest
