apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ghost
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ghost
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: ghost
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/git"
    gitConfig:
      repository: git@github.com:pmh-only/lab.git
      branch: "main"
      writeBackTarget: "kustomization"
  applicationRefs:
    - namePattern: ghost
      images:
        - alias: ghost
          imageName: ghcr.io/pmh-only/ghost:alpine
          commonUpdateSettings:
            updateStrategy: digest
