apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heartbeat
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: heartbeat
    server: https://kubernetes.default.svc
  project: default
  source:
    path: heartbeat
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: heartbeat
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: heartbeat
      images:
        - alias: heartbeat
          imageName: ghcr.io/pmh-only/heartbeat:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: heartbeat-migrator
          imageName: ghcr.io/pmh-only/heartbeat-migrator:latest
          commonUpdateSettings:
            updateStrategy: digest
