apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: here
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: here
    server: https://kubernetes.default.svc
  project: default
  source:
    path: here
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: here
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: here
      images:
        - alias: here
          imageName: ghcr.io/pmh-only/here:latest
          commonUpdateSettings:
            updateStrategy: digest
