apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: immich
    server: https://kubernetes.default.svc
  project: default
  source:
    path: immich
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: immich
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: immich
      images:
        - alias: immich-server
          imageName: ghcr.io/immich-app/immich-server:release
          commonUpdateSettings:
            updateStrategy: digest
        - alias: immich-machine-learning
          imageName: ghcr.io/immich-app/immich-machine-learning:release
          commonUpdateSettings:
            updateStrategy: digest
