apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: indexgen
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: indexgen
    server: https://kubernetes.default.svc
  project: default
  source:
    path: indexgen
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
