apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-router-rbac
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kube-router
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-router
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-router
    helm:
      valuesObject:
        kubeRouter:
          router:
            enabled: false
            enableCni: false
          firewall:
            enabled: true
          serviceProxy:
            enabled: false
          apiServer: "https://10.0.0.10:6443"
          kubeconfig:
            enabled: false
          metricsPort: 20244
        image:
          tag: v2.8.0
    repoURL: https://charts.enix.io
    targetRevision: x
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
