apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: run=ghcr.io/pmh-only/run:latest
    argocd-image-updater.argoproj.io/run.update-strategy: digest
  name: run
  namespace: argocd
spec:
  destination:
    namespace: run
    server: https://kubernetes.default.svc
  project: default
  source:
    path: run
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
