apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotify
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: spotify
    server: https://kubernetes.default.svc
  project: default
  source:
    path: spotify
    repoURL: git@github.com:pmh-only/lab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: spotify
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/git"
    gitConfig:
      repository: git@github.com:pmh-only/lab.git
      branch: "main"
      writeBackTarget: "kustomization"
  applicationRefs:
    - namePattern: spotify
      images:
        - alias: spotify_api
          imageName: ghcr.io/yooooomi/your_spotify_server:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: spotify_web
          imageName: ghcr.io/yooooomi/your_spotify_client:latest
          commonUpdateSettings:
            updateStrategy: digest
