apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailui
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mailui
  template:
    metadata:
      labels:
        app: mailui
    spec:
      containers:
        - name: mailui
          image: ghcr.io/pmh-only/mail:latest
          env:
            - name: DATABASE_URL
              value: /data/local.db
            - name: ORIGIN
              value: https://mail.pmh.codes
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: mailui-secret
                  key: BETTER_AUTH_SECRET
          volumeMounts:
            - mountPath: /data
              name: mailui-pvc
      volumes:
        - name: mailui-pvc
          persistentVolumeClaim:
            claimName: mailui-pvc
