apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mail
resources:
  - ./deployment.yml
  - ./service.yml
  - ./ingress.yml
  - ./pvc.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/mail
    newTag: latest
    digest: sha256:cc68afe07265398155e390146db3e6a1029965d61ed6af557af09b3226100a9f
  - name: ghcr.io/pmh-only/mail-worker
    newTag: latest
    digest: sha256:9ac6b083121d61901818ab0b94fcbe4d1006288dfc832bc26e2bd1c2b5d0d65b
