apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mailui-secret
  namespace: mail
spec:
  template:
    metadata:
      name: mailui-secret
      namespace: mail
  encryptedData:
    BETTER_AUTH_SECRET: AgCi7LzWU1Pz6TdL3oaGfonaBbBXB/iSEJ0Jg0yVm2PyVKhBRuzEYmen2u6Jnk41YjZe7TnYskgWx9Vx6+Vijs4YooJgoNCfeAMtptvlmQv/GL2McEF33FhdSh3l0rK8Tsab+NPnwfy9bNH9UTD7m1VUCtmlBMTxWAqBJHoFWig0Ju1bY/peLJvYWAuIYmenjeBbGKwI5iuRubGCkMLD+laI7iigoOifKVmAijwZMTgwFqp/BaLyauN3Eh0z8W29eOaz/o5VJ9Nlxx+3bW0MoAGtVIecHDr9Y2fjAVxwCP8MEdLB29hHBc8EUm/rEsRcegwbvBz/83PX46vregqJJEUcGMBBmdsCuNqfI6yf2ypK0bZp/30SCZa1Wl4KcN13nedEfE3GTTJsDxfU0pvAX/orbt1vktTSH/4DH+IUe/tfeHmdvx0ydUJoMk46N1lcNMuFDmltdv6OqeaF9v+O9SaqbNiOU3cSz1ockoLtR/w0EEZUoxfX1e19EXSmfgHEFt8+VNtjF+rM2ET0I6cNVTAQTP9SVVfZOPWw9Qu+SwXUT9f12aHgfslXjry0iAH9U2RAHfqIpRcgxBvLnToA7LbgNQWpGdqawdsUkSrNICFGMbw3/gDHjw4a+shLTwAypzB0OwcwZF4AbXaS2OuN7h/EPVF2rEYBS2SxRZDeNEmuK7CfUA3L3pAjwvViMLrj/PtQ3lF1hjH2ZpFvMpozZ7hSsqSv4uNrrSX7KkukHB5EXQ==
