apiVersion: v1
kind: ConfigMap
metadata:
  name: run-config
  namespace: run
data:
  PORT: "8080"
  BASE_URL: "https://run.pmh.codes"
  OIDC_ISSUER_URL: "https://auth.pmh.codes/application/o/run/"
  POD_NAMESPACE: "run"
  POD_IMAGE: "ghcr.io/pmh-only/ubuntu-systemd:24.04"
  POD_SHELL: "/bin/bash"
  POD_CPU_LIMIT: "1000m"
  POD_MEMORY_LIMIT: "2Gi"
  POD_STORAGE_SIZE: "5Gi"
