apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - storageclass.yml
  - runtimeclass.yml
  - rbac.yml
  - configmap.yml
  - secret.yml
  - networkpolicy.yml
  - apparmor-daemonset.yml
  - netpol-daemonset.yml
  - deployment.yml
  - ingress.yml
