apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-run
provisioner: zfs.csi.openebs.io
parameters:
  poolname: "runpool"
  fstype: "ext4"
  compression: "off"
  dedup: "off"
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
