apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - ./secret.yml
  - ./ingress.yml
  - ./certificate.yml
  - ./minio.yml
images:
  - name: ghcr.io/pmh-only/rustfs
    newTag: latest
    digest: sha256:7f40dcee5a2c315e6b3ccb5051fe55855724f708291283f263e236de223e251a
