apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - ./secret.yml
  - ./ingress.yml
  - ./certificate.yml
  - ./minio.yml
images:
  - name: ghcr.io/pmh-only/rustfs
    newTag: latest
    digest: sha256:4507f271f6ecbedaa7a48e203e73f1cfd6a5b41a28bbb0b6d1872dd1eb1a9b18
