apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: gateway
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: gateway
      images:
        - alias: nginx
          imageName: ghcr.io/pmh-only/nginx:latest
          commonUpdateSettings:
            updateStrategy: digest
