apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: immich
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: immich
      images:
        - alias: immich-server
          imageName: ghcr.io/immich-app/immich-server:release
          commonUpdateSettings:
            updateStrategy: digest
        - alias: immich-machine-learning
          imageName: ghcr.io/immich-app/immich-machine-learning:release
          commonUpdateSettings:
            updateStrategy: digest
