apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: minio
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: minio
      images:
        - alias: minio
          imageName: ghcr.io/pmh-only/rustfs:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: explorer
          imageName: ghcr.io/pmh-only/filestash:latest
          commonUpdateSettings:
            updateStrategy: digest
