apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: nameserver
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: nameserver
      images:
        - alias: nameserver
          imageName: ghcr.io/pmh-only/technitium:latest
          commonUpdateSettings:
            updateStrategy: digest
