apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: solver
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: solver
      images:
        - alias: solver
          imageName: ghcr.io/pmh-only/solver:latest
          commonUpdateSettings:
            updateStrategy: digest
