apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: spotify
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: spotify
      images:
        - alias: spotify_api
          imageName: ghcr.io/yooooomi/your_spotify_server:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: spotify_web
          imageName: ghcr.io/yooooomi/your_spotify_client:latest
          commonUpdateSettings:
            updateStrategy: digest
