apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: trace
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: trace
      images:
        - alias: rybbit-backend
          imageName: ghcr.io/rybbit-io/rybbit-backend:latest
          commonUpdateSettings:
            updateStrategy: digest
        - alias: rybbit-client
          imageName: ghcr.io/rybbit-io/rybbit-client:latest
          commonUpdateSettings:
            updateStrategy: digest
