apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: txt
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: txt
      images:
        - alias: txt
          imageName: ghcr.io/pmh-only/txt:latest
          commonUpdateSettings:
            updateStrategy: digest
