apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solver
resources:
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/solver
    newTag: latest
    digest: sha256:d24500351b25f1fd5adf9751bd039084b91e21bf7d8af228bfb63ef31f6fa79b
