apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solver
resources:
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/solver
    newTag: latest
    digest: sha256:0d67dfcc0c201eeb17538f47a0468afceb7a631315cbfffa4d4e7780848804da
