apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solver
resources:
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
  - ./secret.yml
images:
  - name: ghcr.io/pmh-only/solver
    newTag: latest
    digest: sha256:18883efd01495f9740e381b7abe653d242497c12a0cdda80b46c90c8bbcdaa76
