apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: speed
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: speed
      images:
        - alias: speed
          imageName: ghcr.io/librespeed/speedtest:latest-alpine
          commonUpdateSettings:
            updateStrategy: digest
