apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: speed
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
images:
  - name: ghcr.io/librespeed/speedtest
    newTag: latest-alpine
    digest: sha256:fd0d772063820f3f04e82e9d480ddce2ac63493c2ba1abdb82392348c38ba287
