apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: speed
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
images:
  - name: ghcr.io/librespeed/speedtest
    newTag: latest-alpine
    digest: sha256:99efd2aec021887663863c8bbbd58406445ad165f26386df80c647cebcc0adae
