apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: speed
resources:
  - ./secret.yml
  - ./deployment.yml
  - ./service.yml
  - ./pvc.yml
  - ./ingress.yml
images:
  - name: ghcr.io/librespeed/speedtest
    newTag: latest-alpine
    digest: sha256:a9889007bb362e95d14799412cdb5ab0ca3594d44a0730844229a8e83b768389
