---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: speed-secret
  namespace: speed
spec:
  encryptedData:
    IPINFO_APIKEY: AgCwP6ZV/g1JgtsmYDki9HRxfVmFFlUrVMYG6v2GWw8Mookmd0YSUhVxEXfbz5NERspXf+3NbEQ7/SgD/dwhagyPhpmzMxUwi9kG9k48PSZykZC6atYhVvalXP33g31e+uNb+JIAlH/Gm7TfV9ab/IlxyFv+UK7v10pwWXT4de2CqkN4t0lRCT5r0/7lpD3xFQ0trsId4f1KhHz8b+ge1dL1XQ+huch+IwcvQmb5hFTCRJxWcV3pHmHJsDYwSW+IySQMfylDbh2l9JG1hPjECHQ1xMSblNatX4o+z9GQroV89ZSMa6XFOG0HnXAPimUbyfSt8OUNGk5/0mCv4f5WTJXdE47KgrssY9HJlm/fOO4CCKioaMWC+xvm2CKri6UWVgwBUcvD8XQL0+H0ODO+3aJeSDliSsk7+ydr2B4xP8CvAUFMOQGwn1IXUtHu9quHT3pAEiWYBKNwWQsLR99RyC9EygISWGG+f/7tXKVmX0oPJ5cHiBgcXC6JD9wu5MMc5KNxfyywbaSzqVqCNFv/IzJpDAdIb0Pn1wqCw6K41UoAevT7pz1ietWI8WrYmQHGYGEvRQImb2fTX25/UDGZ7uHymCIJCuSOTmxCXpJ9wCsGIUYxmVBiHX9Ecq9fXbQpD8SCzSR8xujg0TQZs+Rwp3h/kawE2BlT0E/lIpjrIf3xagcBBR69oXtPp52qkTNiUTVRuXV5EFQn+4K0jtrf6A==
    PASSWORD: AgALNR/EXYtLlT70jb/qu9JQSwiVFebxHAU9MU6O1T7kzQoh+jPxD1eWmuq8KkRj0e/Ci5K70y8vHnphAFzptqVoOSLTsZzK9wodm5/mXmKjFpnZczlY4jttnEckZvHnqGXnAPtQldEnlPDfLMR/TfnDJ76cSRMWonoS7xxA+tF+1onK+uQZXvAN6jKo4zsw/plE+sdodTIw64x7qMR+WKy9tsXOfVSR7qD8SYv47A8VdMk0GM/puzPwCeSQlC0UQUwjTJV9tPq0/obR3OU038t3ibA/H2QRLxsxAb+TAUTcWioxU7zU0jwamxS845S1VdUA2tH0z9+1CRPml4OWgrxoJoZS1WePeFU4+EnrlUobeqKEzmf3y2Dxz6/mEj7upuK9t1KJs3z4AuZSrkASVhDUb0eZWEGyGaDx6DIrkT80l0mynmBNImAlmhPgonkQvby9mWarSUm05DiPtEXBXYi4vorxVplcGCqN+x18woB3jgMTIH6QiQh7/fm9ha6rS9mu0xfkDcJ2iECREaBsgHZbFZVqBEOQoskcPXmwOH2Bzx0nNjl3YJKSu9c2kLEjdogslEZ+1J+hgqOemkLqr8HPswLKYPTY3Z5H7k0fbh72bsCLOcJl/vBuB/+SfcMYulWKdS4bcZjO+5WxcAgE8+hv8FcoQ2dG2TPEP+Dj9y7RyLlvKAJm6AwKJ2QJZjYQUUH2RAempFFsuTGMw87I8w==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: speed
      name: speed-secret
      namespace: speed
    type: Opaque
