---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stmt-secret
  namespace: stmt
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: AgANU/yLq+dsMZqPl/hX0qdETS8sn/DSJKVJCnQh9cvoFmLqr/9EfAv9cbWwjUk5stz2hRyjoVqi5mgheiTJppG9k+vVa3zRi5LAr+QYITblW7jYKWGmG1+PE0EOStPJlIEqkcXF32LlpSnPqzCHzjJ8w/P/M9qZWkGkIPskSEPpeAzyuTL1mEIuspLxmxkJfqKIjESjOVK5XzB8WzXpstU5RkVk6TZdcVhMiU6MA+q2pNhk0KQPKU28ZnW1hhVl2cpBZcygR+Bwyp2IMZPisFY/nm1YzPDOhvhf/QvUbAiExlhnoAGsViKG34UJ4uImiHnMj2vA0UP8wjJzD27C9tUl1h/ckIk5TPeA750XCCGhMt2uQaw5Md4zkjq1dv2nG4h5DcIw62VylopgVkfhqiXM3u4LQCeXuk/3YRj6nMLTyo4+7B7jj7YcSCC7m2BVTPHxEMkiJEwVJOYGSNRuBey/lvWPChSaraTNdqDDvVZVZnblq1pZz/L6xDYXndh9rCXJYbQM8Ob5RD/VcMg/oB9qkXfFeqDlwI3S5OiFl49x7bFf2oO9qE7l2U1Ct5ntHuYNTDDAsk2+87yp8jDui28uB16BbWfyppi1oPZPE2Xp6iOPwDMmSL5kC1wqHS6MWW8xRkiqvfnFaN+mS/K9FXP4OvMzIT0w1WsiY6yjSU2TDprbuWjOiG8mXvdyic8FBGKAs3GAenNrPVsoUKNRVIc4VjzehlaldhBU0hO63cI64gQqqNNacToP0ba8StQ99KYXQsOG2MzeaL6jP0KxD4LEur75jK7VvfF7bNCGFd5VpRnELQ9bNWZ7YO/A/jksIkZI4j6q42ACC4ID1ACyv1VJ8dWOnEa6ya3fTej5Vl0OaQ==
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: stmt
      name: stmt-secret
      namespace: stmt
    type: Opaque
